language: node_js
node_js:
  - 14
services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed mrmnhat/udagram-api-feed
  - docker tag udagram-api-user mrmnhat/udagram-api-user
  - docker tag udagram-frontend mrmnhat/udagram-frontend
  - docker tag reverseproxy mrmnhat/reverseproxy
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mrmnhat/udagram-api-feed
  - docker push mrmnhat/udagram-api-user
  - docker push mrmnhat/udagram-frontend
  - docker push mrmnhat/reverseproxy
